-- Add migration script here
CREATE TABLE IF NOT EXISTS "sc_germination_codes" (
	"germid"	INTEGER NOT NULL UNIQUE,
	"code"	TEXT NOT NULL,
	"summary"	TEXT,
	"description"	TEXT,
	PRIMARY KEY("germid" AUTOINCREMENT)
);
INSERT INTO "sc_germination_codes" VALUES (1,'A','Seed should germinate upon sowing in a warm location','No pre-treatment necessary other than cold, dry storage') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (2,'B','Hot water treatment','Bring water to a boil, remove from heat, pour over seeds, and soak in a warm place for 24 hours prior to planting.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (3,'C(10)','Seeds germinate after 10 days of cold, moist stratification','Mix seeds with equal amounts or more of damp sand, vermiculite, or other sterile media (moist—but not so wet that water will squeeze out of a handful). We use silica sand (purchased at a building supply center) for small quanti- ties. For large quantities we use coarse grade vermiculite. Place mixture in a labeled, sealed plastic bag and store in a refrigerator (33–38°F). Stratify for the # days indicated in parentheses. If two months (C(60)) of this cold storage before planting is normally required to break the dormancy of these seeds, one month may work for many species if time is a constraint. Some seeds may sprout in the storage bag if moist stratified too long. If sprouting occurs, plant immediately. Another method of breaking dormancy for species requiring moist stratification is to sow seeds outdoors in the fall so they may overwinter.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (4,'C(30)','Seeds germinate after 30 days of cold, moist stratification','Mix seeds with equal amounts or more of damp sand, vermiculite, or other sterile media (moist—but not so wet that water will squeeze out of a handful). We use silica sand (purchased at a building supply center) for small quanti- ties. For large quantities we use coarse grade vermiculite. Place mixture in a labeled, sealed plastic bag and store in a refrigerator (33–38°F). Stratify for the # days indicated in parentheses. If two months (C(60)) of this cold storage before planting is normally required to break the dormancy of these seeds, one month may work for many species if time is a constraint. Some seeds may sprout in the storage bag if moist stratified too long. If sprouting occurs, plant immediately. Another method of breaking dormancy for species requiring moist stratification is to sow seeds outdoors in the fall so they may overwinter.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (5,'C(60)','Seeds germinate after 60 days of cold, moist stratification','Mix seeds with equal amounts or more of damp sand, vermiculite, or other sterile media (moist—but not so wet that water will squeeze out of a handful). We use silica sand (purchased at a building supply center) for small quanti- ties. For large quantities we use coarse grade vermiculite. Place mixture in a labeled, sealed plastic bag and store in a refrigerator (33–38°F). Stratify for the # days indicated in parentheses. If two months (C(60)) of this cold storage before planting is normally required to break the dormancy of these seeds, one month may work for many species if time is a constraint. Some seeds may sprout in the storage bag if moist stratified too long. If sprouting occurs, plant immediately. Another method of breaking dormancy for species requiring moist stratification is to sow seeds outdoors in the fall so they may overwinter.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (6,'C(90)','Seeds germinate after 90 days of cold, moist stratification','Mix seeds with equal amounts or more of damp sand, vermiculite, or other sterile media (moist—but not so wet that water will squeeze out of a handful). We use silica sand (purchased at a building supply center) for small quanti- ties. For large quantities we use coarse grade vermiculite. Place mixture in a labeled, sealed plastic bag and store in a refrigerator (33–38°F). Stratify for the # days indicated in parentheses. If two months (C(60)) of this cold storage before planting is normally required to break the dormancy of these seeds, one month may work for many species if time is a constraint. Some seeds may sprout in the storage bag if moist stratified too long. If sprouting occurs, plant immediately. Another method of breaking dormancy for species requiring moist stratification is to sow seeds outdoors in the fall so they may overwinter.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (7,'C(120)','Seeds germinate after 120 days of cold, moist stratification','Mix seeds with equal amounts or more of damp sand, vermiculite, or other sterile media (moist—but not so wet that water will squeeze out of a handful). We use silica sand (purchased at a building supply center) for small quanti- ties. For large quantities we use coarse grade vermiculite. Place mixture in a labeled, sealed plastic bag and store in a refrigerator (33–38°F). Stratify for the # days indicated in parentheses. If two months (C(60)) of this cold storage before planting is normally required to break the dormancy of these seeds, one month may work for many species if time is a constraint. Some seeds may sprout in the storage bag if moist stratified too long. If sprouting occurs, plant immediately. Another method of breaking dormancy for species requiring moist stratification is to sow seeds outdoors in the fall so they may overwinter.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (8,'D','Seeds are very small or need light to naturally break dormancy and germinate','Seed requiring this treatment should be surface sown - no soil cover or just a dusting of soil should be applied. If grown in outdoor beds, sow stratified (if required) seed on a level surface. Cover with a single layer of burlap or cotton sheet. Remove cover after germination. Do not let soil dry out until seedlings are established. Shading with a window screen set 12” above the soil during the first season will help prevent drying. If sowing seeds in containers, water from the bottom as necessary.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (9,'E','In order to germinate, seeds need a warm, moist period followed by a cold, moist period','Mix seeds with sterile media, place mixture in a labeled, sealed plastic bag and store in warm (about 80°F) place for 60–90 days. Then place in refrigerator (33–38°F) for 60–90 days before sowing. Or, sow outdoors and allow one full year for germination.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (10,'F','Seeds need a cold, moist period followed by a warm, moist period followed by a 2nd cold, moist period','Seeds germinate after alternating, cold moist, warm moist, cold moist stratification treatments. Start by following	 instructions for code C for 60-90 days, then store in a warm (about 80 degrees F) place for 60-90 days, followed by a 2nd cold period in the refrigerator. Or sow outdoors and allow 2 year or longer to germinate.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (11,'G','Seeds germinate most successfully in cool soil','Sow seeds in late fall (after hard frost) or early spring.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (12,'H','Seeds need scarification','Scarify by rubbing seed between two sheets of medium grit sandpaper. Lightly abrade seed coat without crushing seeds. Scarify before stratifying (Code C) if needed.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (13,'I','Legume: Rhizobium inoculum may be added','Most legume species harbor beneficial bacteria called rhizobia on their roots. Genus-specific strains of this bacterium called inoculum can aid in the fixation of atmospheric nitrogen and improve long-term health of native plant communities. Inoculum is naturally-occurring in most soils and additional amendment is usually not needed. However, in low fertility soils, it may be necessary.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (14,'J','Hulls should be removed from seeds','') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (15,'K','Parasitic species which needs a host plant','Good hosts (for many parasitic species) include low-growing grasses and sedges: Hairy Grama, Blue Grama, Pennsylvania Sedge, Little Bluestem, and June Grass. With a knife make a 2” deep cut at the base of the host plant. Sow seed in the cut, making sure seed is not more than 1/8” deep. If host is transplanted at sowing time, the cut is not needed because damaged roots will be available for attachment by the parasite. You may also try sowing parasitic and host species seeds together at the same time. To add parasitic species to existing sites, scatter seed on soil surface (rake in if seed is large) in late fall.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (16,'L','Plant fresh seed or keep moist','Refrigerate until planting or starting other treatment.') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (17,'M','Best planted outdoors in the fall','') ON CONFLICT DO NOTHING;
INSERT INTO "sc_germination_codes" VALUES (18,'O','Impermeable seed coat','Nick seed coat with knife, and soak in water overnight before planting.') ON CONFLICT DO NOTHING;
