[package]
name = "libseed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.26.0"
strum_macros = "0.26.0"
sqlx = { version = "0.8.2", features = [ "sqlite", "runtime-tokio" ] }
tokio = { version = "1.34.0", features = [ "full" ] }
serde = { version = "1.0.193", features = ["serde_derive"] }
anyhow = "1.0.75"
tracing = "0.1.40"
time = { version = "0.3.31", features = ["formatting", "local-offset", "serde", "parsing"] }
password-hash = { version = "0.5.0", features = ["std", "getrandom"] }
argon2 = "0.5.2"
async-trait = "0.1.77"
thiserror = "1.0.56"

[dev-dependencies]
tracing-subscriber = "0.3.18"
test-log = "0.2.14"
