# NOTE: this yaml file should be processed with `envsubst` to provide values for
# the ${variables} below
kind: Secret
apiVersion: v1
metadata:
  name: seedweb-smtp-password
data:
  seedweb-smtp-password: ${SEEDWEB_SMTP_PASSWORD}
---
kind: Pod
apiVersion: v1
metadata:
  name: seedweb
  labels:
    app: seedweb
spec:
  containers:
    - name: app
      args:
        - --env
        - ${SEEDWEB_ENV}
      env:
        - name: SEEDWEB_LOG
          value: ${SEEDWEB_LOG}
        - name: SEEDWEB_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: "seedweb-smtp-password"
              name: "seedweb-smtp-password"
      envFrom:
        - name: SEEDWEB_SMTP_PASSWORD
      image: localhost/seedweb:latest
      ports:
        - containerPort: 8081
      tty: true
      volumeMounts:
        - name: seedweb-db-vol
          mountPath: /usr/share/seedweb/db:Z
        - name: seedweb-config-volume
          mountPath: /etc/seedweb/config.yaml:Z
          readOnly: true

    - name: proxy
      image: docker.io/library/caddy:latest
      ports:
        - containerPort: 443
          hostPort: 8443
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: caddyfile-volume
          mountPath: /etc/caddy/Caddyfile:Z
          readOnly: true
        - name: caddy-data-volume
          mountPath: /data:Z
        - name: caddy-config-volume
          mountPath: /config:Z

    - name: prometheus
      image: docker.io/prom/prometheus:v3.4.0
      ports:
        - name: prometheus-ui
          containerPort: 9090
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
        - name: prometheus-config-vol
          mountPath: /etc/prometheus/prometheus.yml:Z
          readOnly: true
        - name: prometheus-data-vol
          mountPath: /prometheus:Z

    - name: grafana
      image: docker.io/grafana/grafana-oss:12.0.1
      ports:
        - name: grafana-http
          containerPort: 3000
          hostPort: 3000
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
        - name: grafana-provisioning-vol
          mountPath: /etc/grafana/provisioning/datasources/prometheus_ds.yml:Z
          readOnly: true
        - name: grafana-data-volume
          mountPath: /var/lib/grafana:Z

  volumes:
    - name: seedweb-db-vol
      hostPath:
        path: ${SEEDWEB_DATABASE_DIR}
        type: Directory
    - name: seedweb-config-volume
      hostPath:
        path: ./deploy/seedweb-config.yaml
        type: File
    - name: caddyfile-volume
      hostPath:
        path: ./deploy/Caddyfile
        type: File
    - name: caddy-data-volume
      hostPath:
        path: ./deploy/volumes/caddy/local-data
        type: DirectoryOrCreate
    - name: caddy-config-volume
      hostPath:
        path: ./deploy/volumes/caddy/local-config
        type: DirectoryOrCreate
    - name: grafana-provisioning-vol
      hostPath:
        path: ./deploy/grafana.yml
        type: File
    - name: grafana-data-volume
      hostPath:
        path: ./deploy/volumes/grafana/local-data
        type: DirectoryOrCreate
    - name: prometheus-data-vol
      hostPath:
        path: ./deploy/volumes/prometheus/local-data
        type: DirectoryOrCreate
    - name: prometheus-config-vol
      hostPath:
        path: ./deploy/prometheus.yml
        type: File
